spring.application.name: we-ather-spring
spring.profiles.default: local

---
spring:
  config:
    activate:
      on-profile: local

jwt:
  sign: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcEf

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
